module.exports = {
  siteMetadata: {
    htmlLang: "id",
    contenLang: "id",
    title: "TechnoNatura Help Center",
    titleTemplate: "%s · TechnoNatura Help Center",
    description: "Madrasah International TechnoNatura help center page.",
    siteUrl: "https://hc.technonatura.vercel.app",
    siteName: "A Help Center Theme for Gatsby",
    logoUrl: "/images/logo.png",
    logoLabel: "Help Center",
    searchText: "Search",
    faviconUrl: "/images/favicon.png",
    socialSharingImageUrl: "/images/social-sharing-preview.png",
    twitter: "",
    facebookUrl: "",
    ctaButtonText: "TechnoNatura Dashboard",
    ctaButtonUrl: "https://app.technonatura.vercel.app",
    linkText: "Register",
    linkUrl: "https://app.technonatura.vercel.app/register",
    headline: "Apa yang dapat kami bantu?",
    footerText: "Website TechnoNatura",
    footerUrl: "https://technonatura.vercel.app",
    googleTagManagerId: "",
    googleAnalyticsMeasurementId: "",
  },
  plugins: ["gatsby-plugin-typescript", "@mlent/gatsby-theme-help-center"],
};
